const CITY_LIST: [&str; 114] = [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "San Francisco",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington",
    "Boston",
    "El Paso",
    "Nashville Davidson",
    "Detroit",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville Jefferson County",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Mesa",
    "Sacramento",
    "Atlanta",
    "Kansas City",
    "Colorado Springs",
    "Miami",
    "Raleigh",
    "Omaha",
    "Long Beach",
    "Virginia Beach",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Arlington",
    "Tampa",
    "New Orleans",
    "Wichita",
    "Bakersfield",
    "Cleveland",
    "Aurora",
    "Anaheim",
    "Honolulu",
    "Riverside",
    "Santa Ana",
    "Corpus Christi",
    "Lexington Fayette",
    "Henderson",
    "Stockton",
    "Saint Paul",
    "Cincinnati",
    "St. Louis",
    "Pittsburgh",
    "Greensboro",
    "Lincoln",
    "Anchorage",
    "Plano",
    "Orlando",
    "Irvine",
    "Newark",
    "Durham",
    "Chula Vista",
    "Toledo",
    "Fort Wayne",
    "St. Petersburg",
    "Laredo",
    "Jersey City",
    "Chandler",
    "Madison",
    "Lubbock",
    "Scottsdale",
    "Reno",
    "Buffalo",
    "Gilbert",
    "Glendale",
    "North Las Vegas",
    "Winston Salem",
    "Chesapeake",
    "Norfolk",
    "Fremont",
    "Garland",
    "Irving",
    "Hialeah",
    "Richmond",
    "Boise",
    "Spokane",
    "Baton Rouge",
    "Tacoma",
    "San Bernardino",
    "Grand Rapids",
    "Huntsville",
    "Salt Lake City",
    "Frisco",
    "Yonkers",
    "Amarillo",
    "Glendale",
    "McKinney",
    "Montgomery",
    "Aurora",
    "Akron",
    "Little Rock",

];

pub fn generate(rng: &mut impl rand::Rng) -> serde_json::Value {
    let random_number: usize = rng.random_range(0..CITY_LIST.len());

    serde_json::json!(CITY_LIST[random_number])
}
